replicaCount: 1

image:
  repository: miweinho/eggplanned
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: {}
  host: localhost
  path: /

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
