name : Backend Docker build and push 

on:
  push:
    paths:
      - backend/**
    branches: [ main, dev]

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest
    needs: build, test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHRC_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

        # Debugging: List files in the root of the repository to see the directory structure
      - name: List files in the root of the repository
        run: |
          echo "Listing contents of the repository:"
          ls -la

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/plananaz-back:latest -f frontend/Dockerfile frontend

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository_owner }}/plananaz:latest