name: Frontend Docker Build and Push

on:
  push:
    paths:
      - frontend/**
    branches: [main, dev, dev-frontend]
  workflow_run:
    workflows: ["Frontend build and test"] # Der Name des ersten Workflows
    types:
      - completed

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }} # Sicherstellen, dass der Build und Test erfolgreich war

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHRC_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Set image tag
        run: echo "IMAGE_TAG=${{ github.run_number }}" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/plananaz-frontend-image:${{ env.IMAGE_TAG }} -f frontend/Dockerfile frontend

      - name: Tag image with latest
        run: docker tag ghcr.io/${{ github.repository_owner }}/plananaz-frontend-image:${{ env.IMAGE_TAG }} ghcr.io/${{ github.repository_owner }}/plananaz-frontend-image:latest

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository_owner }}/plananaz-frontend-image --all-tags
