name: test_trigger.yaml
on:
  push:
    paths:
      - backend/**
    branches: [ dev-backend ]
  pull_request:
    paths:
      - frontend/**
    branches: [dev-frontend, dev]  
  
jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Trigger GitOps repo workflow
        run: |
          curl -L -v \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GHAC_TOKEN_OPS }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/efficient-and-fun/operation/actions/workflows/trigger_tag_change_backend.yml/dispatches \
            -d '{"ref":"dev","inputs":{"latestSHA":"${{github.sha}}"}}' \
            || echo "Failed with error code $?"