apiVersion: apps/v1
kind: Deployment
metadata:
  name: eggplanned
  labels:
    app: eggplanned
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: eggplanned
  template:
    metadata:
      labels:
        app: eggplanned
    spec:
      containers:
      - name: eggplanned
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 80
