apiVersion: v1
kind: Service
metadata:
  name: eggplanned
  labels:
    app: eggplanned
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: eggplanned